import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'

import Container from '@/components/UI/Container';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <h1>Cloud View</h1>
        </Container>
      </main>
    </>
  )
}
